[package]
name = "core_types"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
strum = "0.27"
strum_macros = "0.27"
serde_json = "1.0.142"
serde = { version = "1.0.219", features = ["derive"] }


