[package]
name = "credentials_storage"
version = "0.1.0"
edition = "2024"

[dependencies]
keyring = { version="3.6.3", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0"
