[package]
name = "file_export"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
sha1 = "0.10.6"
tempfile = "3.19.1"
zip = "2.6.1"
zstd = "0.13.3"
core_types = { path = "../core_types" }
utils = { path = "../utils" }
