name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: "sqlite::memory:?cache=shared"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install GTK4 dependencies
      run: |
        sudo apt-get update 
        sudo apt-get install -y \
          build-essential \
          pkg-config \
          libglib2.0-dev \
          libgtk-4-dev \
          libcairo2-dev \
          libpango1.0-dev \
          libgdk-pixbuf-2.0-dev \
          libgraphene-1.0-dev

    - name: Run database migrations
      run: cargo sqlx migrate run

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
